// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHGohj0QHKVmLOdRnlPCvhEisvWy99OXc',
    appId: '1:265174171794:web:6ca3ae8246934407c2e64b',
    messagingSenderId: '265174171794',
    projectId: 'message-app-ddcef',
    authDomain: 'message-app-ddcef.firebaseapp.com',
    storageBucket: 'message-app-ddcef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcmAbUF3HjRmGQ8rpxjb7Mk_hAWTDBHHI',
    appId: '1:265174171794:android:794e05e08c1bd803c2e64b',
    messagingSenderId: '265174171794',
    projectId: 'message-app-ddcef',
    storageBucket: 'message-app-ddcef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnqE70RQL9cI8jek2nZykcNlAlDzX4oso',
    appId: '1:265174171794:ios:cc86859c2d31e26cc2e64b',
    messagingSenderId: '265174171794',
    projectId: 'message-app-ddcef',
    storageBucket: 'message-app-ddcef.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnqE70RQL9cI8jek2nZykcNlAlDzX4oso',
    appId: '1:265174171794:ios:cc86859c2d31e26cc2e64b',
    messagingSenderId: '265174171794',
    projectId: 'message-app-ddcef',
    storageBucket: 'message-app-ddcef.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHGohj0QHKVmLOdRnlPCvhEisvWy99OXc',
    appId: '1:265174171794:web:750e3bd85b028f79c2e64b',
    messagingSenderId: '265174171794',
    projectId: 'message-app-ddcef',
    authDomain: 'message-app-ddcef.firebaseapp.com',
    storageBucket: 'message-app-ddcef.firebasestorage.app',
  );

}